---
title: "4_plots"
author: "Thomas E. Metherell"
date: "2023-10-26"
format:
    html:
        code-fold: true
        toc: true
---

## Loading dependencies and targets
We first load the dependencies and targets needed to produce the forest plots.

```{r dependencies}
library(targets)
library(data.table)
library(dplyr)
library(forestplot)
library(ggplot2)
library(grid)
library(gridExtra)
library(magrittr)
library(mice)
library(miceadds)
library(purrr)
library(svglite)

data_imputed_binary <- tar_read(data_imputed_binary)
data_imputed_multi <- tar_read(data_imputed_multi)
male_data_binary <- tar_read(male_data_binary)
female_data_binary <- tar_read(female_data_binary)
male_data_multi <- tar_read(male_data_multi)
female_data_multi <- tar_read(female_data_multi)

rutter_5 <- tar_read(rutter_5)
rutter_10 <- tar_read(rutter_10)
cds <- tar_read(cds)
malaise <- tar_read(malaise)
beh_emo <- tar_read(beh_emo)
int_beh <- tar_read(int_beh)
ext_beh <- tar_read(ext_beh)

rutter_5_multi <- tar_read(rutter_5_multi)
rutter_10_multi <- tar_read(rutter_10_multi)
cds_multi <- tar_read(cds_multi)
malaise_multi <- tar_read(malaise_multi)
beh_emo_multi <- tar_read(beh_emo_multi)
int_beh_multi <- tar_read(int_beh_multi)
ext_beh_multi <- tar_read(ext_beh_multi)

rutter_5_med2 <- tar_read(rutter_5_med2)
rutter_10_med2 <- tar_read(rutter_10_med2)
cds_med2 <- tar_read(cds_med2)
malaise_med2 <- tar_read(malaise_med2)
beh_emo_med2 <- tar_read(beh_emo_med2)
int_beh_med2 <- tar_read(int_beh_med2)
ext_beh_med2 <- tar_read(ext_beh_med2)

rutter_5_male <- tar_read(rutter_5_male)
rutter_10_male <- tar_read(rutter_10_male)
cds_male <- tar_read(cds_male)
malaise_male <- tar_read(malaise_male)
beh_emo_male <- tar_read(beh_emo_male)
int_beh_male <- tar_read(int_beh_male)
ext_beh_male <- tar_read(ext_beh_male)

rutter_5_female <- tar_read(rutter_5_female)
rutter_10_female <- tar_read(rutter_10_female)
cds_female <- tar_read(cds_female)
malaise_female <- tar_read(malaise_female)
beh_emo_female <- tar_read(beh_emo_female)
int_beh_female <- tar_read(int_beh_female)
ext_beh_female <- tar_read(ext_beh_female)

rutter_5_multi_male <- tar_read(rutter_5_multi_male)
rutter_10_multi_male <- tar_read(rutter_10_multi_male)
cds_multi_male <- tar_read(cds_multi_male)
malaise_multi_male <- tar_read(malaise_multi_male)
beh_emo_multi_male <- tar_read(beh_emo_multi_male)
int_beh_multi_male <- tar_read(int_beh_multi_male)
ext_beh_multi_male <- tar_read(ext_beh_multi_male)

rutter_5_multi_female <- tar_read(rutter_5_multi_female)
rutter_10_multi_female <- tar_read(rutter_10_multi_female)
cds_multi_female <- tar_read(cds_multi_female)
malaise_multi_female <- tar_read(malaise_multi_female)
beh_emo_multi_female <- tar_read(beh_emo_multi_female)
int_beh_multi_female <- tar_read(int_beh_multi_female)
ext_beh_multi_female <- tar_read(ext_beh_multi_female)

rutter_5_med2_male <- tar_read(rutter_5_med2_male)
rutter_10_med2_male <- tar_read(rutter_10_med2_male)
cds_med2_male <- tar_read(cds_med2_male)
malaise_med2_male <- tar_read(malaise_med2_male)
beh_emo_med2_male <- tar_read(beh_emo_med2_male)
int_beh_med2_male <- tar_read(int_beh_med2_male)
ext_beh_med2_male <- tar_read(ext_beh_med2_male)

rutter_5_med2_female <- tar_read(rutter_5_med2_female)
rutter_10_med2_female <- tar_read(rutter_10_med2_female)
cds_med2_female <- tar_read(cds_med2_female)
malaise_med2_female <- tar_read(malaise_med2_female)
beh_emo_med2_female <- tar_read(beh_emo_med2_female)
int_beh_med2_female <- tar_read(int_beh_med2_female)
ext_beh_med2_female <- tar_read(ext_beh_med2_female)
```

## Defining plotting functions
We can now define the functions used to produce the individual plots.

```{r plotting_functions}
# Forest plot for binary results
results_fp <- function(results, current_dep_var, title, xticks){
    forestplot(
        results[results$dep_var == current_dep_var,],
        labeltext = c(ind_var, RR.rounded, p.rounded, E.rounded),
        boxsize = 0.2,
        xlab = "Risk ratio (standardised)",
        xticks = c(0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0),
        zero = 1,
        title = title
    ) %>%
        fp_add_lines() %>%
        fp_set_style(align = "lccc") %>%
        fp_add_header(
            ind_var = "Variable", 
            RR.rounded = fp_align_center("RR"),
            p.rounded = fp_align_center("p"), 
            E.rounded = fp_align_center("E-value")
        )
}

# Forest plot for multinomial results
multi_results_fp <- function(multi_results, current_dep_var, current_group, title, xticks){
    forestplot(
      multi_results[multi_results$dep_var == current_dep_var & multi_results$group == current_group,],
      labeltext = c(ind_var, RRR.rounded, p.rounded, E.rounded),
      boxsize = 0.2,
      xlab = "Relative risk ratio (standardised)",
      xticks = c(1.0, 1.5, 2, 2.5, 3, 3.5, 4),
      zero = 1,
      title = title
    ) %>%
        fp_add_lines() %>%
        fp_set_style(align = "lccc") %>%
        fp_add_header(
          ind_var = "Variable",
          RRR.rounded = fp_align_center("RRR"),
          p.rounded = fp_align_center("p"), 
          E.rounded = fp_align_center("E-value")
        )
}

# Forest plot for mediation analysis results
med_results_fp <- function(med_results, current_dep_var, title, xticks){
    forestplot(
      med_results[med_results$dep_var == current_dep_var,],
      labeltext = c(ind_var, RR.rounded, p.rounded, E.rounded),
      boxsize = 0.2,
      xlab = "Risk ratio (standardised)",
      xticks = xticks,
      zero = 1,
      title = title
    ) %>%
        fp_add_lines() %>%
        fp_set_style(align = "lccc") %>%
        fp_add_header(
            ind_var = "Variable", 
            RR.rounded = fp_align_center("RR"),
            p.rounded = fp_align_center("p"),
            E.rounded = fp_align_center("E-value")
        )
}
```

```{r lists}
ind_vars <- c("rutter_5", "rutter_10", "cds", "malaise", "beh_emo", "int_beh", "ext_beh")
ind_var_names <- c("d119", "BD3MRUTT", "dv_cds_10", "BD4MAL", "rd6m_1", "intbcsz", "extbcsz")
```

```{r binary}
results <- mget(ind_vars) %>% reduce(rbind)

for(var in unique(results$ind_var)){
    stdev <- sqrt(withPool_MI(with(data_imputed_binary, sd(get(var)))))
    results[results$ind_var == var,]$RR <- results[results$ind_var == var,]$RR ^ stdev
    results[results$ind_var == var,]$RR.LCI <- results[results$ind_var == var,]$RR.LCI ^ stdev
    results[results$ind_var == var,]$RR.UCI <- results[results$ind_var == var,]$RR.UCI ^ stdev
}

results %<>%
    mutate(
        Evalue = case_when(
            RR.UCI < 1 ~ (1/RR.UCI) + sqrt((1/RR.UCI)*((1/RR.UCI) - 1)),
            RR.LCI > 1 ~ RR.LCI + sqrt(RR.LCI*(RR.LCI - 1)),
            TRUE ~ 1
        ),
        RR.rounded = sprintf("%.3f", round(RR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RR, lower = RR.LCI, upper = RR.UCI)

fp1 <- grid.grabExpr(print(results_fp(results, "dv_sr_sleep_abn", "Self-reported average", xticks = c(0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0))))
fp2 <- grid.grabExpr(print(results_fp(results, "dv_sd_sleep_abn", "Diary-derived average", xticks = c(0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0))))
fp3 <- grid.grabExpr(print(results_fp(results, "dv_pal_sleep_abn", "activPAL algorithm", xticks = c(0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0))))     
fp4 <- grid.grabExpr(print(results_fp(results, "dv_vdb_sleep_abn", "van der Berg et al. algorithm", xticks = c(0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0))))
fp5 <- grid.grabExpr(print(results_fp(results, "dv_winkler_sleep_abn", "Winkler et al. algorithm", xticks = c(0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0))))

plotgrid <- gridExtra::grid.arrange(fp1, fp2, fp3, fp4, fp5, ncol = 1)
ggsave("plots/binary/forestplots.svg", plotgrid, height = 29.7, width = 21, units = "cm")
```

```{r multi}
multi_results <- mget(paste(ind_vars, "multi", sep = "_")) %>% reduce(rbind)

for(var in unique(multi_results$ind_var)){
    stdev <- sqrt(withPool_MI(with(data_imputed_multi, sd(get(var)))))
    multi_results[multi_results$ind_var == var,]$RRR <- multi_results[multi_results$ind_var == var,]$RRR ^ stdev
    multi_results[multi_results$ind_var == var,]$RRR.LCI <- multi_results[multi_results$ind_var == var,]$RRR.LCI ^ stdev
    multi_results[multi_results$ind_var == var,]$RRR.UCI <- multi_results[multi_results$ind_var == var,]$RRR.UCI ^ stdev
}

multi_results %<>% 
    mutate(
        Evalue = case_when(
            RRR.UCI < 1 ~ (1/RRR.UCI) + sqrt((1/RRR.UCI)*((1/RRR.UCI) - 1)),
            RRR.LCI > 1 ~ RRR.LCI + sqrt(RRR.LCI*(RRR.LCI - 1)),
            TRUE ~ 1
        ),
        RRR.rounded = sprintf("%.3f", round(RRR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RRR, lower = RRR.LCI, upper = RRR.UCI)

fp6 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_sr_sleep_abn_cat", "Short", "Self-reported average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp7 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_sd_sleep_abn_cat", "Short", "Diary-derived average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp8 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_pal_sleep_abn_cat", "Short", "activPAL algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp9 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_vdb_sleep_abn_cat", "Short", "van der Berg et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp10 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_winkler_sleep_abn_cat", "Short", "Winkler et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))

short_plotgrid <- gridExtra::grid.arrange(fp6, fp7, fp8, fp9, fp10, top = textGrob("Abnormally short sleep duration", gp = gpar(fontsize = 18)), ncol = 1)

fp11 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_sr_sleep_abn_cat", "Long", "Self-reported average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp12 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_sd_sleep_abn_cat", "Long", "Diary-derived average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp13 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_pal_sleep_abn_cat", "Long", "activPAL algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp14 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_vdb_sleep_abn_cat", "Long", "van der Berg et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp15 <- grid.grabExpr(print(multi_results_fp(multi_results, "dv_winkler_sleep_abn_cat", "Long", "Winkler et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))

long_plotgrid <- gridExtra::grid.arrange(fp11, fp12, fp13, fp14, fp15, top = textGrob("Abnormally long sleep duration", gp = gpar(fontsize = 18)), ncol = 1)

combinedmulti_plotgrid <- gridExtra::grid.arrange(short_plotgrid, long_plotgrid, ncol = 1)
ggsave("plots/multi/combinedmulti_forestplots.svg", combinedmulti_plotgrid, height = 59.4, width = 21, units = "cm")
```

```{r med}
med_results <- mget(paste(ind_vars, "med2", sep = "_")) %>% reduce(rbind)

for(var in unique(med_results$ind_var)){
    stdev <- sqrt(withPool_MI(with(data_imputed_binary, sd(get(var)))))
    med_results[med_results$ind_var == var,]$RR <- med_results[med_results$ind_var == var,]$RR ^ stdev
    med_results[med_results$ind_var == var,]$RR.LCI <- med_results[med_results$ind_var == var,]$RR.LCI ^ stdev
    med_results[med_results$ind_var == var,]$RR.UCI <- med_results[med_results$ind_var == var,]$RR.UCI ^ stdev
}

med_results %<>%
    mutate(
        Evalue = case_when(
            RR.UCI < 1 ~ (1/RR.UCI) + sqrt((1/RR.UCI)*((1/RR.UCI) - 1)),
            RR.LCI > 1 ~ RR.LCI + sqrt(RR.LCI*(RR.LCI - 1)),
            TRUE ~ 1
        ),
        RR.rounded = sprintf("%.3f", round(RR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RR, lower = RR.LCI, upper = RR.UCI)

fp16 <- grid.grabExpr(print(med_results_fp(med_results, "dv_sr_sleep_abn", "Self-reported average", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp17 <- grid.grabExpr(print(med_results_fp(med_results, "dv_sd_sleep_abn", "Diary-derived average", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp18 <- grid.grabExpr(print(med_results_fp(med_results, "dv_pal_sleep_abn", "activPAL algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp19 <- grid.grabExpr(print(med_results_fp(med_results, "dv_vdb_sleep_abn", "van der Berg et al. algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp20 <- grid.grabExpr(print(med_results_fp(med_results, "dv_winkler_sleep_abn", "Winkler et al. algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))

med_plotgrid <- gridExtra::grid.arrange(fp16, fp17, fp18, fp19, fp20, ncol = 1)
ggsave("plots/mediation/med_forestplots.svg", med_plotgrid, height = 29.7, width = 21, units = "cm")
```

```{r binary_male}
male_results <- mget(paste(ind_vars, "male", sep = "_")) %>% reduce(rbind)

for(var in unique(male_results$ind_var)){
    stdev <- sqrt(withPool_MI(with(male_data_binary, sd(get(var)))))
    male_results[male_results$ind_var == var,]$RR <- male_results[male_results$ind_var == var,]$RR ^ stdev
    male_results[male_results$ind_var == var,]$RR.LCI <- male_results[male_results$ind_var == var,]$RR.LCI ^ stdev
    male_results[male_results$ind_var == var,]$RR.UCI <- male_results[male_results$ind_var == var,]$RR.UCI ^ stdev
}

male_results %<>%
    mutate(
        Evalue = case_when(
            RR.UCI < 1 ~ (1/RR.UCI) + sqrt((1/RR.UCI)*((1/RR.UCI) - 1)),
            RR.LCI > 1 ~ RR.LCI + sqrt(RR.LCI*(RR.LCI - 1)),
            TRUE ~ 1
        ),
        RR.rounded = sprintf("%.3f", round(RR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RR, lower = RR.LCI, upper = RR.UCI)

fp21 <- grid.grabExpr(print(results_fp(male_results, "dv_sr_sleep_abn", "Self-reported average", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))
fp22 <- grid.grabExpr(print(results_fp(male_results, "dv_sd_sleep_abn", "Diary-derived average", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))
fp23 <- grid.grabExpr(print(results_fp(male_results, "dv_pal_sleep_abn", "activPAL algorithm", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))     
fp24 <- grid.grabExpr(print(results_fp(male_results, "dv_vdb_sleep_abn", "van der Berg et al. algorithm", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))
fp25 <- grid.grabExpr(print(results_fp(male_results, "dv_winkler_sleep_abn", "Winkler et al. algorithm", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))

male_plotgrid <- gridExtra::grid.arrange(fp21, fp22, fp23, fp24, fp25, ncol = 1)
ggsave("plots/binary/male_forestplots.svg", male_plotgrid, height = 29.7, width = 21, units = "cm")
```

```{r binary_female}
female_results <- mget(paste(ind_vars, "female", sep = "_")) %>% reduce(rbind)

for(var in unique(female_results$ind_var)){
    stdev <- sqrt(withPool_MI(with(female_data_binary, sd(get(var)))))
    female_results[female_results$ind_var == var,]$RR <- female_results[female_results$ind_var == var,]$RR ^ stdev
    female_results[female_results$ind_var == var,]$RR.LCI <- female_results[female_results$ind_var == var,]$RR.LCI ^ stdev
    female_results[female_results$ind_var == var,]$RR.UCI <- female_results[female_results$ind_var == var,]$RR.UCI ^ stdev
}

female_results %<>%
    mutate(
        Evalue = case_when(
            RR.UCI < 1 ~ (1/RR.UCI) + sqrt((1/RR.UCI)*((1/RR.UCI) - 1)),
            RR.LCI > 1 ~ RR.LCI + sqrt(RR.LCI*(RR.LCI - 1)),
            TRUE ~ 1
        ),
        RR.rounded = sprintf("%.3f", round(RR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RR, lower = RR.LCI, upper = RR.UCI)

fp26 <- grid.grabExpr(print(results_fp(female_results, "dv_sr_sleep_abn", "Self-reported average", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))
fp27 <- grid.grabExpr(print(results_fp(female_results, "dv_sd_sleep_abn", "Diary-derived average", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))
fp28 <- grid.grabExpr(print(results_fp(female_results, "dv_pal_sleep_abn", "activPAL algorithm", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))     
fp29 <- grid.grabExpr(print(results_fp(female_results, "dv_vdb_sleep_abn", "van der Berg et al. algorithm", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))
fp30 <- grid.grabExpr(print(results_fp(female_results, "dv_winkler_sleep_abn", "Winkler et al. algorithm", c(0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2))))

female_plotgrid <- gridExtra::grid.arrange(fp26, fp27, fp28, fp29, fp30, ncol = 1)
ggsave("plots/binary/female_forestplots.svg", female_plotgrid, height = 29.7, width = 21, units = "cm")
```

```{r multi_male}
multi_male_results <- mget(paste(ind_vars, "multi_male", sep = "_")) %>% reduce(rbind)

for(var in unique(multi_male_results$ind_var)){
    stdev <- sqrt(withPool_MI(with(male_data_multi, sd(get(var)))))
    multi_male_results[multi_male_results$ind_var == var,]$RRR <- multi_male_results[multi_male_results$ind_var == var,]$RRR ^ stdev
    multi_male_results[multi_male_results$ind_var == var,]$RRR.LCI <- multi_male_results[multi_male_results$ind_var == var,]$RRR.LCI ^ stdev
    multi_male_results[multi_male_results$ind_var == var,]$RRR.UCI <- multi_male_results[multi_male_results$ind_var == var,]$RRR.UCI ^ stdev
}

multi_male_results %<>% 
    mutate(
        Evalue = case_when(
            RRR.UCI < 1 ~ (1/RRR.UCI) + sqrt((1/RRR.UCI)*((1/RRR.UCI) - 1)),
            RRR.LCI > 1 ~ RRR.LCI + sqrt(RRR.LCI*(RRR.LCI - 1)),
            TRUE ~ 1
        ),
        RRR.rounded = sprintf("%.3f", round(RRR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RRR, lower = RRR.LCI, upper = RRR.UCI)

fp31 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_sr_sleep_abn_cat", "Short", "Self-reported average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp32 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_sd_sleep_abn_cat", "Short", "Diary-derived average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp33 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_pal_sleep_abn_cat", "Short", "activPAL algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp34 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_vdb_sleep_abn_cat", "Short", "van der Berg et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp35 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_winkler_sleep_abn_cat", "Short", "Winkler et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))

short_plotgrid <- gridExtra::grid.arrange(fp31, fp32, fp33, fp34, fp35, top = textGrob("Abnormally short sleep duration", gp = gpar(fontsize = 18)), ncol = 1)

fp36 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_sr_sleep_abn_cat", "Long", "Self-reported average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp37 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_sd_sleep_abn_cat", "Long", "Diary-derived average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp38 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_pal_sleep_abn_cat", "Long", "activPAL algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp39 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_vdb_sleep_abn_cat", "Long", "van der Berg et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp40 <- grid.grabExpr(print(multi_results_fp(multi_male_results, "dv_winkler_sleep_abn_cat", "Long", "Winkler et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))

long_plotgrid <- gridExtra::grid.arrange(fp36, fp37, fp38, fp39, fp40, top = textGrob("Abnormally long sleep duration", gp = gpar(fontsize = 18)), ncol = 1)

male_combinedmulti_plotgrid <- gridExtra::grid.arrange(short_plotgrid, long_plotgrid, ncol = 1)
ggsave("plots/multi/male_combinedmulti_forestplots.svg", male_combinedmulti_plotgrid, height = 59.4, width = 21, units = "cm")
```

```{r multi_female}
multi_female_results <- mget(paste(ind_vars, "multi_female", sep = "_")) %>% reduce(rbind)

for(var in unique(multi_female_results$ind_var)){
    stdev <- sqrt(withPool_MI(with(female_data_multi, sd(get(var)))))
    multi_female_results[multi_female_results$ind_var == var,]$RRR <- multi_female_results[multi_female_results$ind_var == var,]$RRR ^ stdev
    multi_female_results[multi_female_results$ind_var == var,]$RRR.LCI <- multi_female_results[multi_female_results$ind_var == var,]$RRR.LCI ^ stdev
    multi_female_results[multi_female_results$ind_var == var,]$RRR.UCI <- multi_female_results[multi_female_results$ind_var == var,]$RRR.UCI ^ stdev
}

multi_female_results %<>% 
    mutate(
        Evalue = case_when(
            RRR.UCI < 1 ~ (1/RRR.UCI) + sqrt((1/RRR.UCI)*((1/RRR.UCI) - 1)),
            RRR.LCI > 1 ~ RRR.LCI + sqrt(RRR.LCI*(RRR.LCI - 1)),
            TRUE ~ 1
        ),
        RRR.rounded = sprintf("%.3f", round(RRR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RRR, lower = RRR.LCI, upper = RRR.UCI)

fp41 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_sr_sleep_abn_cat", "Short", "Self-reported average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp42 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_sd_sleep_abn_cat", "Short", "Diary-derived average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp43 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_pal_sleep_abn_cat", "Short", "activPAL algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp44 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_vdb_sleep_abn_cat", "Short", "van der Berg et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp45 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_winkler_sleep_abn_cat", "Short", "Winkler et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))

short_plotgrid <- gridExtra::grid.arrange(fp41, fp42, fp43, fp44, fp45, top = textGrob("Abnormally short sleep duration", gp = gpar(fontsize = 18)), ncol = 1)

fp46 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_sr_sleep_abn_cat", "Long", "Self-reported average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp47 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_sd_sleep_abn_cat", "Long", "Diary-derived average", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp48 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_pal_sleep_abn_cat", "Long", "activPAL algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp49 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_vdb_sleep_abn_cat", "Long", "van der Berg et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))
fp50 <- grid.grabExpr(print(multi_results_fp(multi_female_results, "dv_winkler_sleep_abn_cat", "Long", "Winkler et al. algorithm", c(1.0, 1.5, 2, 2.5, 3, 3.5, 4))))

long_plotgrid <- gridExtra::grid.arrange(fp46, fp47, fp48, fp49, fp50, top = textGrob("Abnormally long sleep duration", gp = gpar(fontsize = 18)), ncol = 1)

female_combinedmulti_plotgrid <- gridExtra::grid.arrange(short_plotgrid, long_plotgrid, ncol = 1)
ggsave("plots/multi/female_combinedmulti_forestplots.svg", female_combinedmulti_plotgrid, height = 59.4, width = 21, units = "cm")
```

```{r med_male}
med_male_results <- mget(paste(ind_vars, "med2_male", sep = "_")) %>% reduce(rbind)

for(var in unique(med_male_results$ind_var)){
    stdev <- sqrt(withPool_MI(with(data_imputed_binary, sd(get(var)))))
    med_male_results[med_male_results$ind_var == var,]$RR <- med_male_results[med_male_results$ind_var == var,]$RR ^ stdev
    med_male_results[med_male_results$ind_var == var,]$RR.LCI <- med_male_results[med_male_results$ind_var == var,]$RR.LCI ^ stdev
    med_male_results[med_male_results$ind_var == var,]$RR.UCI <- med_male_results[med_male_results$ind_var == var,]$RR.UCI ^ stdev
}

med_male_results %<>%
    mutate(
        Evalue = case_when(
            RR.UCI < 1 ~ (1/RR.UCI) + sqrt((1/RR.UCI)*((1/RR.UCI) - 1)),
            RR.LCI > 1 ~ RR.LCI + sqrt(RR.LCI*(RR.LCI - 1)),
            TRUE ~ 1
        ),
        RR.rounded = sprintf("%.3f", round(RR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RR, lower = RR.LCI, upper = RR.UCI)

fp51 <- grid.grabExpr(print(med_results_fp(med_male_results, "dv_sr_sleep_abn", "Self-reported average", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp52 <- grid.grabExpr(print(med_results_fp(med_male_results, "dv_sd_sleep_abn", "Diary-derived average", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp53 <- grid.grabExpr(print(med_results_fp(med_male_results, "dv_pal_sleep_abn", "activPAL algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp54 <- grid.grabExpr(print(med_results_fp(med_male_results, "dv_vdb_sleep_abn", "van der Berg et al. algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp55 <- grid.grabExpr(print(med_results_fp(med_male_results, "dv_winkler_sleep_abn", "Winkler et al. algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))

med_male_plotgrid <- gridExtra::grid.arrange(fp51, fp52, fp53, fp54, fp55, ncol = 1)
ggsave("plots/mediation/med_male_forestplots.svg", med_male_plotgrid, height = 29.7, width = 21, units = "cm")
```

```{r med_female}
med_female_results <- mget(paste(ind_vars, "med2_female", sep = "_")) %>% reduce(rbind)

for(var in unique(med_female_results$ind_var)){
    stdev <- sqrt(withPool_MI(with(data_imputed_binary, sd(get(var)))))
    med_female_results[med_female_results$ind_var == var,]$RR <- med_female_results[med_female_results$ind_var == var,]$RR ^ stdev
    med_female_results[med_female_results$ind_var == var,]$RR.LCI <- med_female_results[med_female_results$ind_var == var,]$RR.LCI ^ stdev
    med_female_results[med_female_results$ind_var == var,]$RR.UCI <- med_female_results[med_female_results$ind_var == var,]$RR.UCI ^ stdev
}

med_female_results %<>%
    mutate(
        Evalue = case_when(
            RR.UCI < 1 ~ (1/RR.UCI) + sqrt((1/RR.UCI)*((1/RR.UCI) - 1)),
            RR.LCI > 1 ~ RR.LCI + sqrt(RR.LCI*(RR.LCI - 1)),
            TRUE ~ 1
        ),
        RR.rounded = sprintf("%.3f", round(RR, 3)),
        p.rounded = sprintf("%.3f", round(p, 3)),
        E.rounded = sprintf("%.3f", round(Evalue, 3)),
        ind_var = case_when(
            ind_var == "rd6m_1" ~ "Behavioural & emotional problems (16)",
            ind_var == "dv_cds_10" ~ "Child Development Scale (10)",
            ind_var == "extbcsz" ~ "Externalising behaviours (16)",
            ind_var == "intbcsz" ~ "Internalising behaviours (16)",
            ind_var == "BD4MAL" ~ "Malaise score (16)",
            ind_var == "d119" ~ "Rutter score (5)",
            ind_var == "BD3MRUTT" ~ "Rutter score (10)"
        )
    ) %>%
    rename(mean = RR, lower = RR.LCI, upper = RR.UCI)

fp56 <- grid.grabExpr(print(med_results_fp(med_female_results, "dv_sr_sleep_abn", "Self-reported average", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp57 <- grid.grabExpr(print(med_results_fp(med_female_results, "dv_sd_sleep_abn", "Diary-derived average", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp58 <- grid.grabExpr(print(med_results_fp(med_female_results, "dv_pal_sleep_abn", "activPAL algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp59 <- grid.grabExpr(print(med_results_fp(med_female_results, "dv_vdb_sleep_abn", "van der Berg et al. algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))
fp60 <- grid.grabExpr(print(med_results_fp(med_female_results, "dv_winkler_sleep_abn", "Winkler et al. algorithm", c(0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6))))

med_female_plotgrid <- gridExtra::grid.arrange(fp56, fp57, fp58, fp59, fp60, ncol = 1)
ggsave("plots/mediation/med_female_forestplots.svg", med_female_plotgrid, height = 29.7, width = 21, units = "cm")
```